CREATE DATABASE project1;
USE project1;

-- =========================
-- TABLE CREATION
-- =========================

CREATE TABLE Customers (
    customer_id INT PRIMARY KEY,
    name VARCHAR(50),
    phone VARCHAR(15)
);

CREATE TABLE Bikes (
    bike_id INT PRIMARY KEY,
    model VARCHAR(50),
    type VARCHAR(20),
    rent_per_day INT,
    status VARCHAR(20)
);

CREATE TABLE Rentals (
    rental_id INT PRIMARY KEY,
    customer_id INT,
    bike_id INT,
    rent_date DATE,
    return_date DATE,
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id),
    FOREIGN KEY (bike_id) REFERENCES Bikes(bike_id)
);

CREATE TABLE Payments (
    payment_id INT PRIMARY KEY,
    rental_id INT,
    amount INT,
    payment_date DATE,
    FOREIGN KEY (rental_id) REFERENCES Rentals(rental_id)
);

-- =========================
-- SAMPLE DATA
-- =========================

INSERT INTO Customers VALUES
(1, 'Rahul', '1111111111'),
(2, 'Amit', '2222222222'),
(3, 'Sneha', '3333333333'),
(4, 'Priya', '4444444444'),
(5, 'Karan', '5555555555'),
(6, 'Neha', '6666666666'),
(7, 'Arjun', '7777777777'),
(8, 'Meera', '8888888888');

INSERT INTO Bikes VALUES
(101, 'Activa 6G', 'Scooter', 400, 'Available'),
(102, 'Jupiter', 'Scooter', 450, 'Rented'),
(103, 'Royal Enfield', 'Cruiser', 1200, 'Rented'),
(104, 'Pulsar 220', 'Sports', 800, 'Available'),
(105, 'KTM Duke', 'Sports', 1500, 'Available'),
(106, 'Access 125', 'Scooter', 500, 'Available'),
(107, 'Apache RTR', 'Sports', 900, 'Rented'),
(108, 'Honda Shine', 'Commuter', 350, 'Available');

INSERT INTO Rentals VALUES
(201, 1, 102, '2026-04-01', '2026-04-03'),
(202, 2, 103, '2026-04-05', NULL),
(203, 1, 104, '2026-04-10', '2026-04-12'),
(204, 3, 102, '2026-04-15', '2026-04-18'),
(205, 4, 103, '2026-04-20', NULL),
(206, 5, 107, '2026-04-08', '2026-04-11'),
(207, 6, 106, '2026-04-12', '2026-04-14'),
(208, 7, 108, '2026-04-18', NULL);

INSERT INTO Payments VALUES
(301, 201, 900, '2026-04-03'),
(302, 203, 1600, '2026-04-12'),
(303, 204, 1350, '2026-04-18'),
(304, 206, 2700, '2026-04-11'),
(305, 207, 1000, '2026-04-14'),
(306, 202, 2400, '2026-04-07'),
(307, 205, 3600, '2026-04-22');

-- =========================
-- 20 SQL QUERIES
-- =========================

-- 1. Retrieve all available bikes.
SELECT bike_id, model, rent_per_day
FROM Bikes
WHERE status = 'Available';

-- 2. Find all ongoing rentals (not yet returned).
SELECT rental_id, customer_id, bike_id, rent_date
FROM Rentals
WHERE return_date IS NULL;

-- 3. Find total number of bikes in the system.
SELECT COUNT(*) AS total_bikes
FROM Bikes;

-- 4. Display customer name along with bike model and rent date.
SELECT c.name, b.model, r.rent_date
FROM Rentals r
JOIN Customers c ON r.customer_id = c.customer_id
JOIN Bikes b ON r.bike_id = b.bike_id;

-- 5. Calculate total revenue generated by each bike.
SELECT b.model, SUM(p.amount) AS total_revenue
FROM Bikes b
JOIN Rentals r ON b.bike_id = r.bike_id
JOIN Payments p ON r.rental_id = p.rental_id
GROUP BY b.model;

-- 6. Find total amount spent by each customer.
SELECT c.name, SUM(p.amount) AS total_spent
FROM Customers c
JOIN Rentals r ON c.customer_id = r.customer_id
JOIN Payments p ON r.rental_id = p.rental_id
GROUP BY c.name;

-- 7. Count how many times each bike has been rented.
SELECT bike_id, COUNT(*) AS rental_count
FROM Rentals
GROUP BY bike_id;

-- 8. Find the most rented bike.
SELECT bike_id, COUNT(*) AS total_rentals
FROM Rentals
GROUP BY bike_id
ORDER BY total_rentals DESC
LIMIT 1;

-- 9. Find bikes that have never been rented.
SELECT model
FROM Bikes
WHERE bike_id NOT IN (SELECT bike_id FROM Rentals);

-- 10. Find customers who have never rented a bike.
SELECT name
FROM Customers
WHERE customer_id NOT IN (SELECT customer_id FROM Rentals);

-- 11. Find bikes whose rent per day is higher than average.
SELECT model, rent_per_day
FROM Bikes
WHERE rent_per_day > (SELECT AVG(rent_per_day) FROM Bikes);

-- 12. Find rentals that do not have any payment recorded.
SELECT r.rental_id
FROM Rentals r
LEFT JOIN Payments p ON r.rental_id = p.rental_id
WHERE p.payment_id IS NULL;

-- 13. Find the customer who has spent the maximum amount.
SELECT c.name, SUM(p.amount) AS total_spent
FROM Customers c
JOIN Rentals r ON c.customer_id = r.customer_id
JOIN Payments p ON r.rental_id = p.rental_id
GROUP BY c.name
ORDER BY total_spent DESC
LIMIT 1;

-- 14. Find rentals where total payment is greater than average payment.
SELECT rental_id, SUM(amount) AS total_payment
FROM Payments
GROUP BY rental_id
HAVING SUM(amount) > (SELECT AVG(amount) FROM Payments);

-- 15. Find all rentals that lasted more than 2 days.
SELECT rental_id, rent_date, return_date
FROM Rentals
WHERE return_date IS NOT NULL
AND DATEDIFF(return_date, rent_date) > 2;

-- 16. Find the bike currently rented for the longest time.
SELECT b.model, DATEDIFF(CURDATE(), r.rent_date) AS days_rented
FROM Rentals r
JOIN Bikes b ON r.bike_id = b.bike_id
WHERE r.return_date IS NULL
ORDER BY days_rented DESC
LIMIT 1;

-- 17. Perform an update and rollback the changes.
START TRANSACTION;

UPDATE Bikes
SET rent_per_day = 999
WHERE bike_id = 101;

ROLLBACK;

-- 18. Perform an update and commit the changes.
START TRANSACTION;

UPDATE Bikes
SET rent_per_day = 450
WHERE bike_id = 101;

COMMIT;

-- 19. Grant permission to a user to read bike data.
SHOW GRANTS FOR CURRENT_USER;

-- 20. Revoke permission from the user.
SELECT CURRENT_USER();